### ISSUE TITLE
Hope to increase the ability to access the author's open Avatar

### ISSUE THREAD

**Issue by miaopasimiao** [kichiro1337/vrchat_useful_mod#1]
Hope to increase the ability to access the author's open Avatar.Like this
![4OWWZQ `A0(17{{Y$VTE6@K](https://user-images.githubusercontent.com/35228123/80793634-3b229c00-8bca-11ea-9b76-ebc99a678525.png)

There used to be a plug-in that can use this function, but now it is no longer available.

**Comment by kichiro1337** [comment]
I can look into doing this, this would require extended API access though, was this plugin open-source before?

A link if it was would be nice, I could just update that plugin instead.

**Comment by miaopasimiao** [comment]
This plug-in is modified based on avatarfav

https://drive.google.com/open?id=1M9nnda6p_Iew2tNzLkacROdWlET_22Yi

**Comment by kichiro1337** [comment]
Small update on this, currently not possible to do due to the unhallower having some issues with the objects and conversions.

I will come back to this idea though once that stuff is solved.

**Comment by kichiro1337** [comment]
https://github.com/kichiro1337/vrchat_useful_mod/releases/tag/1.3.3.7(15)
This was added, thank you for the idea!
