### ISSUE TITLE
Crash when i leave menu and move around

### ISSUE THREAD

**Issue by InactiveCoyote** [kichiro1337/vrchat_useful_mod#11]
it keeps crashing when i move around and pressing the esc to leave the menu. fix

**Comment by kichiro1337** [comment]
Any particular steps to reproduce that error?

Tried walking around while the menu is open but that just results in it closing as expected.

**Comment by InactiveCoyote** [comment]
i did every step to download but i use melonloader when i open the menu then i press the esc key or move around the box dissapears but the options still show then it crashes

**Comment by kichiro1337** [comment]
Sounds to me like some kinda installation issue, make sure to also check VRChat for errors.

**Comment by InactiveCoyote** [comment]
what errors theres nothing wrong with it.
