### ISSUE TITLE
Noclip / Fly bug

### ISSUE THREAD

**Issue by ghosteReverse** [kichiro1337/vrchat_useful_mod#12]
Noclip/fly function will send you in the direction that is inputted, but will not toggle off in that direction. 
This leaves you in motion perpetually, even sometimes unable to use the escape menu.

Tested on 2 computers, with 2 instances, by 2 people. (desktop mode)

**Comment by kichiro1337** [comment]
Hence it changes the gravity you would need to go against the direction you are going, I might be able to change that at some point.
