### ISSUE TITLE
Not showing in the quick menu and errors showing in console

### ISSUE THREAD

**Issue by NepuShiro** [kichiro1337/vrchat_useful_mod#13]
The error I'm getting is
`[useful_stuff_mod] Error in the main routine! QuickMenu QuickMenu.Method_Public_Static_get_QuickMenu_0() in TestMod Stack:   at TestMod.remake.funcs.menu.menu.version_info () [0x00000] in <cb2360e8e0c64c998da868993734f3dc>:0`
I'm either guessing this isn't compatible with Emmvrc or I've just done something wrong
![image](https://user-images.githubusercontent.com/64931347/81232426-84079580-8fba-11ea-84d1-b38a2b6165a4.png)

**Comment by kichiro1337** [comment]
Install the managed folder correctly, read the installation steps.
