### ISSUE TITLE
Crash when i leave menu and move around

### ISSUE THREAD

**Issue by InactiveCoyote** [kichiro1337/vrchat_useful_mod#15]
https://github.com/kichiro1337/vrchat_useful_mod/issues/11

you cant close it if its not resolved

**Comment by kichiro1337** [comment]
Not a issue caused by me, something about your installation is wrong - this isn't reproduce-able in any way.

**Comment by InactiveCoyote** [comment]
what am i supposed to do i fllowed everything i uninstalled vrchat and reinstall it and it still crashes when i move or leave the menu.

**Comment by InactiveCoyote** [comment]
https://github.com/kichiro1337/vrchat_useful_mod/issues/8

they also have Same Problem.

**Comment by gibmadikka** [comment]
I can confirm that the crashing is still happening with the newest version of the mod uploaded 3 hours ago. I have only installed your mod with MelonLoader, nothing else is in the folder. Updated the assembly managed folder too from you.

The VRChat logfiles show this at the end.

> 2020.05.07 05:41:47 Exception  -  NullReferenceException: Object reference not set to an instance of an object.
ShortcutMenu.Start () (at <00000000000000000000000000000000>:0)

**Comment by kichiro1337** [comment]
hash#0404 contact me.

**Comment by kichiro1337** [comment]
Issues resolved, you both are using Oculus client which is not fully supported.
