### ISSUE TITLE
Error when booting up VR.

### ISSUE THREAD

**Issue by WraecIast** [kichiro1337/vrchat_useful_mod#16]
I don't know if this is an issue with the mod, Melonloader, or VRChat itself.

Everytime I load up the game MelonLoader boots up, says the mod is up to date, then VRChat gives me an Error and immediately closes.

I've tried verifying the game files in Steam to see if VRChat was the issue, but still no fix.

**Comment by kichiro1337** [comment]
Did you re-install the mod for the latest version including the managed files?

**Comment by WraecIast** [comment]
> Did you re-install the mod for the latest version including the managed files?

This was an issue on my end, thank you for replying. I just updated the managed folder right before you commented. The issue is now fixed.
