### ISSUE TITLE
Log assets file

### ISSUE THREAD

**Issue by Canloo** [kichiro1337/vrchat_useful_mod#17]
Hey ur doing an amazing job so far. Huge thumbs up.

But I have one request if that's even possible.
When we log assets, is it possible to save it somewhere else? Because when I check the melonloader log, it's impossible to find anything. Atleast for me.
And add maybe like avtr id if that works?

**Comment by kichiro1337** [comment]
You can enable the debug console of melonloader by adding the launch parameter "--melonloader.console" to VRChat.

Then you will have a debug console which will display it right when you click the button, which makes it easier to catch.

There will be a function to add avatars by avatar id in the next update as well - it will also display the asset URL and avatar name in the console.
