### ISSUE TITLE
[Suggestion] Join notifications

### ISSUE THREAD

**Issue by gibmadikka** [kichiro1337/vrchat_useful_mod#20]
Hello, I would like to suggest a joining notification option. For example when someone new joins you can define a sound and/or show a text somewhere ingame which you can define yourself. Maybe the same for leaving would be a nice addition too. Thank you again for the mod, hope that skiddos won't trash this with their CuStOm WrItTeN cLiEnTs

**Comment by kichiro1337** [comment]
Noted, might come in the future.

Thanks!
