### ISSUE TITLE
Fov glitched out

### ISSUE THREAD

**Issue by itreallydobelikethat** [kichiro1337/vrchat_useful_mod#23]
**Describe the bug**
Well it's quite simple, when you change your fov and if you accidentally mess it up, there's no way of resetting it. This has made it impossible for me to play the game without having to remove the mod.

**To Reproduce**
1. Go to 'Open Menu'
2. Click on 'Next Page'
3. Max out the 'Fov'

**Expected behavior**
Well I was hoping that it would reset after a relog but turns out that it saves. Now I'm unaware of the fact that where it actually saves.

**Screenshots**
![image](https://user-images.githubusercontent.com/65071446/81472113-40f23000-920f-11ea-82cc-d291094b735a.png)

**Additional context**

**Comment by itreallydobelikethat** [comment]
I just looked at the existing issues and it turns out that you can edit the hashcfg.ini file to reset the fov. My bad, you can close this issue. :)

**Comment by kichiro1337** [comment]
Glad you found the solution!
