### ISSUE TITLE
Global Dynamics Fail To Work

### ISSUE THREAD

**Issue by OFWModz** [kichiro1337/vrchat_useful_mod#25]
**Describe the bug**
Upon adding dynamics to a user, nothing changes, even though my avatar has a collider per joint in hand.
I have tried purging cache, nothing makes them work.

**To Reproduce**
Simply click on a user, add dynamics and watch them fail to work - A factor may be my model does have many colliders in each hand, one per joint including the wrist.

**Expected behavior**
Dynamics actually working.

**Comment by kichiro1337** [comment]
More testing with dynamic bones will be done today, it is still very experimental keep in mind.

Changing your avatar once can help it currently for whatever reason, still looking to fix that and a bunch more.

Thanks for reporting in though!

**Comment by kichiro1337** [comment]
Resolved in https://github.com/kichiro1337/vrchat_useful_mod/commit/2d525532554f68b1f1da395e8ded3fafcc4e7f9d
