### ISSUE TITLE
A few more simple issues..

### ISSUE THREAD

**Issue by OFWModz** [kichiro1337/vrchat_useful_mod#26]
version_info() is not present in type menu
make_slider is not present in type make_slider

sln file is not supplied in source among other files for successful forks to be done easily.

**Comment by OFWModz** [comment]
And now input_text in type menu.

**Comment by kichiro1337** [comment]
sln will not be supplied, if you know how to compile things you should have no issue reconstructing it.
Missing methods will be added, thanks!
