### ISSUE TITLE
Dynamic Bones fail to cross-reference and self-reference

### ISSUE THREAD

**Issue by NarKirsch** [kichiro1337/vrchat_useful_mod#29]
**Describe the bug**
1. Cross-referencing on multiple instances: in case there's more than one instance of the same avatar, only the first instance will be processed; late spawners will be ignored, even if explicitly forced to cross-reference.
2. Suspecting that it may be caused by the failure to assign remote colliders to local avatar instance. Local avatar instances are always skipped, thus making it impossible for one to see remote colliders interact with local dynbones.

**To Reproduce**
Steps to reproduce cross-reference issue:
1. Get 2 or more people in the same instance
2. All participants must clone the same avatar
3. Enable collisions with any of the participants
4. Attempt to interact with selected targets

Steps to reproduce self-reference issue:
1. Use any avatar with dynamic bones
2. Enable collisions with remote player
3. Optionally find a mirror, otherwise use a camera to see own bones
4. Ask remote player to attempt to interact with your avatar's instance

**Expected behavior**
**Cross-reference:** must be independent of the instance and/or currently used local avatar. All instances of an avatar should be able to interact with each other's dynamic bones.  
**Self-reference:** as simple as it gets--it just should react like remote client's dynamic bones react to yours/their colliders interacting with anyone else.

**Comment by kichiro1337** [comment]
Nope they are local only.
Since the il2cpp patch it shouldn't be possible anymore.

Someone might find a workaround for that though.

**Comment by NarKirsch** [comment]
Please elaborate on what seems to be impossible, as this response doesn't really resolve anything, nor does it have anything to do with the current (and all existing) implementation.

The colliders are local only, that isn't the matter of question. The actual fetching and Collider collection assignment is.

Like I said, right now multiple instances of the same avatar causes all cross-references to fail, which isn't the expected behaviour.

In addition, like I stated in item 2, local avatar instance (the one used by local client) fails to cross-reference remote (other players') colliders properly. This, at the very least, seems like an unintended behaviour.

**Comment by kichiro1337** [comment]
This is just a test build of that system, it will be expanded there sure are bugs like that which will be resolved.
