### ISSUE TITLE
Fav+ reverse order

### ISSUE THREAD

**Issue by fwenny** [kichiro1337/vrchat_useful_mod#3]
Everytime I launch VRC, the avatars in Fav+ appear in the opposite order than the json.

The second I fav or unfav any avatar, it gets fixed, but next launch it is reverse order again.

Not a big deal but a bit annoying when you want your newly fav'd avatars on the left most side.

**Comment by kichiro1337** [comment]
Yup, I see what the issue is there - fixed in the next release in a second here.

Thanks!

**Comment by kichiro1337** [comment]
Fixed in commit

https://github.com/kichiro1337/vrchat_useful_mod/commit/3fd2d32a7b6436711570e3ac96000e76d86958cd
