### ISSUE TITLE
[Feature request] Toggling buttons on or off

### ISSUE THREAD

**Issue by fwenny** [kichiro1337/vrchat_useful_mod#30]
Could you add the option (in the cfg for example) to toggle certain buttons on or off?
For example, I want to remove the Teleport button in User page, etc.

**Comment by kichiro1337** [comment]
Are you talking about emmVRC having a button there as well by any chance?
If so they allow you to move the button in their config.

**Comment by kichiro1337** [comment]
If not, yeah I could do that at some point.
