### ISSUE TITLE
IK Fix Feature

### ISSUE THREAD

**Issue by basicgodly** [kichiro1337/vrchat_useful_mod#34]
Seen this feature around a lot pre-il2cpp but no one has really touched this feature atm, basically re-alligns your viewpoint to your head when you go into a sitting animation, because your viewpoint goes into your chest normally.
![VRChat_2020-05-13_22-15-31](https://user-images.githubusercontent.com/46283142/81860551-36190180-9567-11ea-83da-14f4e129f775.png)

Would be nice to look into.

**Comment by kichiro1337** [comment]
Might take a look at that in the future, thanks for the idea!
