### ISSUE TITLE
[Request] Changing public avatar order

### ISSUE THREAD

**Issue by fwenny** [kichiro1337/vrchat_useful_mod#35]
Could you make it so avatars are returned based on their Last Update status so the most recently updated ones will be at the top?

Currently order seems very random.

**Comment by kichiro1337** [comment]
That's how the API gives them to me supposed to be newest first.

**Comment by fwenny** [comment]
You can provide an argument to the API asking to order it by Update Date.

**Comment by fwenny** [comment]
You can provide an argument to the API asking to order it by Update Date.

**Comment by kichiro1337** [comment]
Got it, thanks.

Will be there whenever the next patch drops.
