### ISSUE TITLE
Shader Menu overlaps with UI

### ISSUE THREAD

**Issue by basicgodly** [kichiro1337/vrchat_useful_mod#36]
Button for the '''Show Shader Menu''' overlaps with room owner buttons, suggesting you put it on that one last free space.
![VRChat_2020-05-14_03-36-50](https://user-images.githubusercontent.com/46283142/81882911-26fc7880-9594-11ea-8fb3-7c9260a8a9e8.png)

**Comment by kichiro1337** [comment]
I will be putting them in a own menu for the next patch.

Thanks for letting me know though!
