### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Dryesthalo98066** [kichiro1337/vrchat_useful_mod#38]
Anti avatar hud
![Capture](https://user-images.githubusercontent.com/54002516/81987279-4da7c700-9607-11ea-9d01-d1a72af636cf.PNG)

**Comment by kichiro1337** [comment]
Would be hard to pull off, as the HUD itself must be called something recognize able like 'HUD' for me to find it, and block it.

So most likely not, thanks for the idea though!
