### ISSUE TITLE
when i launch the game after installing it there is no menu to access the mod

### ISSUE THREAD

**Issue by Blitzen61** [kichiro1337/vrchat_useful_mod#4]
I put the download in the mod folder but when i launch the game there is no tab to open the mod menu.

**Comment by kichiro1337** [comment]
You need to install the unhallowed files, which are linked in the installation instruction in the readme file.
Follow those and you will be good to go!
https://github.com/kichiro1337/vrchat_useful_mod/blob/master/README.md

**Comment by DragunsRcool** [comment]
I have this same issue and i've followed the optional steps but i still can't get the button to appear on the quick menu
