### ISSUE TITLE
anti portal is simply not working 

### ISSUE THREAD

**Issue by Broslayeragain** [kichiro1337/vrchat_useful_mod#40]
**Describe the bug**
well anti portal isn't working its not doing anything rn
**To Reproduce**
just have the function on ?

**Expected behavior**
portals just appears even if you have the function on. 

**Screenshots**
![bild](https://user-images.githubusercontent.com/47481447/81989934-6aabbc80-963e-11ea-9fd4-74e33b405738.png)

**Additional context**
its been happening on the lastest versions of them mod i figured il just talk about it. it might be something that happen during the new update but pls fix this it was very very useful thx. even if i restart its not working

**Comment by kichiro1337** [comment]
Disable ignore friends and that should be fine again.
As ignore friends now ignores any friends portals. Which would also be you.

**Comment by Broslayeragain** [comment]
ima try it but when i was in a public world it let even non friends to put down portals

**Comment by Broslayeragain** [comment]
aight it worked sry for the hassle

**Comment by kichiro1337** [comment]
No problem!
