### ISSUE TITLE
[Bug] Expanded collider doesnt work

### ISSUE THREAD

**Issue by fwenny** [kichiro1337/vrchat_useful_mod#41]
Hey. I saw you wrote this:
Expanded collider for direct-menu to possibly prevent the bug where "Show shader menu" can not be clicked anymore for whatever reason.

The result is that I still cant click the menu, but also some of the buttons from other mods have moved one row down, overlapping other buttons.

**Comment by kichiro1337** [comment]
Odd, I will be moving the button into the user options page then there will be no issue.

Thanks for letting me know!
