### ISSUE TITLE
problem with message user

### ISSUE THREAD

**Issue by Dryesthalo98066** [kichiro1337/vrchat_useful_mod#43]
![Capture](https://user-images.githubusercontent.com/54002516/82102289-1dcaf300-96dd-11ea-9a66-73a16b564a05.PNG)
whenever you try to send your self a message may occur with messaging others have not tested it the menu does not close.

**Comment by Broslayeragain** [comment]
wait you cant msg your self ? how the hell did you do that

**Comment by kichiro1337** [comment]
How do you want to message yourself? lol

**Comment by kichiro1337** [comment]
Let me know how exactly you did that

**Comment by Dryesthalo98066** [comment]
I using emm lmao you can select yourself

**Comment by Broslayeragain** [comment]
try to restart or reinstall your stuff cause i was able to without this happening

**Comment by Broslayeragain** [comment]
ohh i see thats actually a problem when trying to send a msg in public after sending a few msgs it will make the menu get stuck and it will continue getting stuck when going into the pause menu

**Comment by kichiro1337** [comment]
Yup I see i will be trying to fix that

**Comment by ItsByMeVRC** [comment]
where is the log stuff stored?

**Comment by kichiro1337** [comment]
VRchat/Logs in the latest log file
