### ISSUE TITLE
use MD5 hashes for shaders, use whitelist instead of blacklist

### ISSUE THREAD

**Issue by untuned** [kichiro1337/vrchat_useful_mod#44]
**Is your feature request related to a problem? Please describe.**
A crasher could modify the shader name to remove it from the blacklist, and even then it should be a whitelist for known safe shaders.

**Describe the solution you'd like**
A list of MD5 hashes in a whitelisted file, along with the name of the shader so people know what it is. Include buttons to whitelist a user (show their shaders regardless), blacklist (move them to all standard shaders), and dump shaders (gets the hash and name of all shaders on the avatar).

**Describe alternatives you've considered**
None.

**Additional context**
Was a feature of VRCAntiCrash before the 2018 update. Existing whitelist file: https://github.com/OFWModz/VRCShaderWhitelist/blob/master/WhitelistedMD5List

**Comment by kichiro1337** [comment]
Neat idea but I'm not changing the current way, it's good enough.
