### ISSUE TITLE
[Potential bug?] AddFav+ issue

### ISSUE THREAD

**Issue by fwenny** [kichiro1337/vrchat_useful_mod#46]
I dont know if its intentional or not, but this caused more issues than good for me.

If I click on a person, User options, Add avatar to AddFav and the avatar already exists in the list, it removes it. I dont think this should be the case, it should only add, or do nothing if its already in the list (maybe even reflect somehow that the avatar is already favorited?)

Thanks

**Comment by kichiro1337** [comment]
Resolved in latest update, thanks!
