### ISSUE TITLE
Is this more missing methods?

### ISSUE THREAD

**Issue by OFWModz** [kichiro1337/vrchat_useful_mod#47]
![ScreenShot_20200521091448](https://user-images.githubusercontent.com/36628963/82580229-cc13e400-9b86-11ea-914b-053cf31ddae1.png)

**Comment by OFWModz** [comment]
![sc](https://user-images.githubusercontent.com/36628963/82580926-bc48cf80-9b87-11ea-8118-37df028d5bd8.png)
Yet more

**Comment by kichiro1337** [comment]
Do not come back here skid.
