### ISSUE TITLE
Fav+ issues with private / deleted avatars

### ISSUE THREAD

**Issue by fwenny** [kichiro1337/vrchat_useful_mod#5]
atm trying to remove an unavailable avatar does nothing. 

Furthermore theres no indication that the avatar is unavailable. Changing the thumbnail / text would be helpful

**Comment by kichiro1337** [comment]
Solved in https://github.com/kichiro1337/vrchat_useful_mod/commit/8938a1931462f1dc2bf6fef4b7fa256b595e6652

Thanks!
