### ISSUE TITLE
Show public avatars button

### ISSUE THREAD

**Issue by fwenny** [kichiro1337/vrchat_useful_mod#6]
If I try clicking the button again after clicking it once, it does nothing for awhile. 

Im guessing theres a hidden cooldown tied to the button, so I think it should be reflected by disabling the button, and maybe adding a small display of seconds counting down next to it so you know when its next available.

**Comment by kichiro1337** [comment]
Yup there is a cool-down to it, I will add a countdown inside of the button when not available sounds useful. (1 minute cooldown)

Thanks!

**Comment by fwenny** [comment]
How come its 1 minute? Wasnt the VRC limit 30 seconds or so?

**Comment by kichiro1337** [comment]
From what I could read about it it is 60 seconds.

**Comment by fwenny** [comment]
Oh okay. Better safe than sorry then.
