### ISSUE TITLE
[Suggestions] Couple suggestions

### ISSUE THREAD

**Issue by fwenny** [kichiro1337/vrchat_useful_mod#7]
1. If possible add an expander for the buttons / move the buttons to a separate area in the user info page so they dont always overlap the users public worlds.

2. Adding a button to social page refresh would be amazing.

3. Add a button to user info page to show public avatars so we dont have to fav an avatar to use the button.

4. Option to disable chairs / pickups globally

5. Per player microphone volume

6. Switch between optimized and full mirrors at will

Just some ideas. =)

**Comment by kichiro1337** [comment]
Will keep this in mind, thanks!
