### ISSUE TITLE
New vrc update broke the mod

### ISSUE THREAD

**Issue by gibmadikka** [kichiro1337/vrchat_useful_mod#8]
Hello, the mod won't work anymore as of todays vrchat 1.1p5 update. Could you please update this awesome mod? Thank you very much! :)

**Comment by kichiro1337** [comment]
Updated, reinstall the mod and the managed folder again.

**Comment by gibmadikka** [comment]
Hello thanks for the update! Although whenever you open the menu and then try to close it (both in desktop and VR) it crashes the game. I have used the updated dll and new assembly files you uploaded.
