### ISSUE TITLE
Quickmenu/compatibility

### ISSUE THREAD

**Issue by TeriKuruzu** [kichiro1337/vrchat_useful_mod#9]
With the recent release of EmmVRC in open beta, i thought i'd couple it with the mod you made. it needed the default unhollower to work, which means i cannot make any changes to the managed folder without emmvrc breaking. However, it works with a clean install of melonloader. Now, the qol mod you made seems to load, but comes with this message in the log if i try to run it alongside emmvrc:

 Error in the main routine! QuickMenu QuickMenu.Method_Public_Static_get_QuickMenu_0() in TestMod Stack:   at TestMod.remake.funcs.menu.menu.version_info () [0x00000] in <cb2360e8e0c64c998da868993734f3dc>:0
  at TestMod.hashmod.OnUpdate () [0x00000] in <cb2360e8e0c64c998da868993734f3dc>:0

**Comment by fwenny** [comment]
Yeah I can confirm that using the Manged linked here makes the mod work, but breaks emmVRC.
Using the newly generated Managed folder makes emmVRC work, but breaks this.

Is there any way you can make the mod work with the new Manged files?

**Comment by kichiro1337** [comment]
No, emmVRC uses version 0.2 I use 0.3.
They need to update to 0.3, nothing I can do.
